  [[redirects]]
  from = "https://memint.me"
  to = "https://www.memint.xyz"
  status = 301
  force = true

  [[redirects]]
  from = "https://www.memint.me"
  to = "https://www.memint.xyz"
  status = 301
  force = true

[[redirects]]
  from = "https://goodnodes.netlify.app"
  to = "https://www.memint.xyz"
  status = 301
  force = true